### ISSUE TITLE
chore(release): create release for node 4+ support fix

### ISSUE THREAD

**Issue by Splaktar** [cmanzana/node-figaro#12]
Should this be a 1.10.0 release?

**Comment by cmanzana** [comment]
Sorry, forgot to push the change (2714486a59cd58ebcc9fff238714bbe9a5dec11f)
and I guess you mean 0.1.10

**Comment by Splaktar** [comment]
Doh, yes `0.1.10` sorry.

**Comment by Splaktar** [comment]
Created the `0.1.10` tag and [release](https://github.com/cmanzana/node-figaro/releases/tag/v0.1.10).
