### ISSUE TITLE
If installed before Node 0.12.x, will break when updating to Node 0.12.x

### ISSUE THREAD

**Issue by Thesephi** [cmanzana/node-figaro#5]
Currently the `ursa` dependency is stated as exactly `0.8.x`. This causes an old installation of `figaro` to **not** automatically update `ursa` to its latest version `0.8.3` (at the time this isssue is created) which works well with Node 0.12.x. Maybe we should add a tilde character (changing it to `~0.8.x`) to prevent things like this from happening again? If you'd love to, I could help with the pull request!

**Comment by cmanzana** [comment]
Hi! by all means do a pull request and fix it :-)
